package pojos;
// Generated 2021.03.05. 7:47:36 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImdbTop1000 generated by hbm2java
 */
@Entity
@Table(name="imdb_top1000"
    ,catalog="imdb_top1000"
)
public class ImdbTop1000  implements java.io.Serializable {


     private int id;
     private String title;
     private Integer releasedYear;
     private String certificate;
     private Integer runtime;
     private String genre;
     private BigDecimal imdbRating;
     private String overview;
     private Integer metaScore;
     private String director;
     private String star;
     private String star1;
     private String star2;
     private String star3;
     private String star4;
     private Integer noOfVotes;
     private Long gross;

    public ImdbTop1000() {
    }

	
    public ImdbTop1000(int id) {
        this.id = id;
    }
    public ImdbTop1000(int id, String title, Integer releasedYear, String certificate, Integer runtime, String genre, BigDecimal imdbRating, String overview, Integer metaScore, String director, String star, String star1, String star2, String star3, String star4, Integer noOfVotes, Long gross) {
       this.id = id;
       this.title = title;
       this.releasedYear = releasedYear;
       this.certificate = certificate;
       this.runtime = runtime;
       this.genre = genre;
       this.imdbRating = imdbRating;
       this.overview = overview;
       this.metaScore = metaScore;
       this.director = director;
       this.star = star;
       this.star1 = star1;
       this.star2 = star2;
       this.star3 = star3;
       this.star4 = star4;
       this.noOfVotes = noOfVotes;
       this.gross = gross;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Title", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="Released_Year")
    public Integer getReleasedYear() {
        return this.releasedYear;
    }
    
    public void setReleasedYear(Integer releasedYear) {
        this.releasedYear = releasedYear;
    }

    
    @Column(name="Certificate", length=45)
    public String getCertificate() {
        return this.certificate;
    }
    
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    
    @Column(name="Runtime")
    public Integer getRuntime() {
        return this.runtime;
    }
    
    public void setRuntime(Integer runtime) {
        this.runtime = runtime;
    }

    
    @Column(name="Genre", length=45)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }

    
    @Column(name="IMDB_Rating", precision=2, scale=1)
    public BigDecimal getImdbRating() {
        return this.imdbRating;
    }
    
    public void setImdbRating(BigDecimal imdbRating) {
        this.imdbRating = imdbRating;
    }

    
    @Column(name="Overview")
    public String getOverview() {
        return this.overview;
    }
    
    public void setOverview(String overview) {
        this.overview = overview;
    }

    
    @Column(name="Meta_score")
    public Integer getMetaScore() {
        return this.metaScore;
    }
    
    public void setMetaScore(Integer metaScore) {
        this.metaScore = metaScore;
    }

    
    @Column(name="Director", length=100)
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }

    
    @Column(name="Star", length=100)
    public String getStar() {
        return this.star;
    }
    
    public void setStar(String star) {
        this.star = star;
    }

    
    @Column(name="Star1", length=100)
    public String getStar1() {
        return this.star1;
    }
    
    public void setStar1(String star1) {
        this.star1 = star1;
    }

    
    @Column(name="Star2", length=100)
    public String getStar2() {
        return this.star2;
    }
    
    public void setStar2(String star2) {
        this.star2 = star2;
    }

    
    @Column(name="Star3", length=100)
    public String getStar3() {
        return this.star3;
    }
    
    public void setStar3(String star3) {
        this.star3 = star3;
    }

    
    @Column(name="Star4", length=100)
    public String getStar4() {
        return this.star4;
    }
    
    public void setStar4(String star4) {
        this.star4 = star4;
    }

    
    @Column(name="No_of_Votes")
    public Integer getNoOfVotes() {
        return this.noOfVotes;
    }
    
    public void setNoOfVotes(Integer noOfVotes) {
        this.noOfVotes = noOfVotes;
    }

    
    @Column(name="Gross")
    public Long getGross() {
        return this.gross;
    }
    
    public void setGross(Long gross) {
        this.gross = gross;
    }




}


